spring.application.name=spring-ai-ollama
server.port = 8081
spring.ai.ollama.base-url = http://127.0.0.1:11434/
spring.ai.ollama.chat.options.model = codellama:latest
spring.ai.ollama.chat.options.temperature=0.7
#spring.ai.ollama.chat.options.max-tokens=2048


#spring.ai.openai.api-key=sk-xxxxxxxxxxxxxxxx
#spring.ai.openai.chat.options.model=gpt-5

# Google Gemini API Key
spring.ai.google.genai.api-key=AQ.Ab8RN6L_h8XMoOHxnd-5taCXEZR5XJK8og8YcmlyJUw4ov3e_Q

# Model
spring.ai.google.genai.chat.options.model=gemini-2.5-flash